global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'agentic-api'
    static_configs:
      - targets: ['api-server:8000']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'agentic-mcp'
    static_configs:
      - targets: ['mcp-server:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 10s
